name:                advent-of-code2023
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/advent-of-code2023#readme
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2023 Author name here
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NumericUnderscores
  - RankNTypes
  - RecordWildCards
  - OverloadedRecordDot
  - OverloadedStrings
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeOperators

dependencies:
  - base >= 4.7 && < 5
  - array
  - attoparsec
  - clock
  - containers
  - formatting
  - hashable
  - heap
  - regex-tdfa
  - split
  - text
  - unordered-containers
  - vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  advent-of-code2023:
    source-dirs:      src
    main:             Main.hs

library:
  source-dirs: src
  exposed-modules:
    - Solutions.Day01
    - Solutions.Day02
    - Solutions.Day03
    - Solutions.Day04
    - Solutions.Day05
    - Solutions.Day06
    - Solutions.Day07
    - Solutions.Day08
    - Solutions.Day09
    - Solutions.Day11
    - Solutions.Day12

tests:
  unit-test:
    main: Driver.hs
    source-dirs:
      - test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - tasty
      - tasty-hunit
      - advent-of-code2023
    language: Haskell2010
    build-tools:
      - tasty-discover

